version: '3'
services:
  homepage:
    build:
      context: ../../../
      dockerfile: ./apps/homepage/docker/Dockerfile
    user: 'root'
    environment:
      - CDN_URL=
      - INVSEARCH_V3_URL=https://invsearch-v3-prod-ext.aws.vroomapi.com/v3
    command: ash -c 'yarn install && yarn workspace @vroom-web/ui build && yarn workspace @vroom-web/homepage dev --port 8080'
    ports:
      - '8080:8080'
    volumes:
      - '../../../:/www/:cached'
      # stop dependencies and build artifacts from copying to host
      - '/www/apps/homepage/.next'
      - '/www/apps/homepage/node_modules'
      - '/www/libs/ui/dist'
      - '/www/libs/ui/node_modules'
