version: '3'
services:
  web:
    build:
      context: ../../../
      dockerfile: ./apps/homepage/docker/Dockerfile
    user: 'root'
    environment:
      - CDN_URL=
      - INVSEARCH_V3_URL=https://invsearch-v3-prod-ext.aws.vroomapi.com/v3
    command: ash -c './apps/homepage/docker/setup.sh && yarn --cwd ./apps/homepage dev --port 8080'
    ports:
      - '8080:8080'
    volumes:
      # Link everything in library folders, except dependencies and build artifacts.
      - '../../../libs/ui/:/www/libs/ui/:cached'
      - '/www/libs/ui/dist'
      - '/www/libs/ui/node_modules'

      # Link everything in the app folder, except for dependencies and build artifacts.
      - '../:/www/apps/homepage/:cached'
      - '/www/apps/homepage/.next'
      - '/www/apps/homepage/node_modules'
