export const CommonTypes = {
  SET_PHONE_NUMBER: '/common/SET_PHONE_NUMBER',
  SERVER_PREFETCH_FAILED: '/common/SERVER_PREFETCH_FAILED',
  SHOW_ERROR: '/common/SHOW_ERROR',
  HIDE_ERROR: '/common/HIDE_ERROR',
  SHOW_SUCCESS: '/common/SHOW_SUCCESS',
  HIDE_SUCCESS: '/common/HIDE_SUCCESS',
  SHOW_SNACKBAR: '/common/SHOW_SNACKBAR',
  SET_UTM_PARAMS: '/common/SET_UTM_PARAMS',
  SET_GCLID_PARAM: '/common/SET_GCLID_PARAM',
  SET_SUBID_PARAM: '/common/SET_SUBID_PARAM',
  SET_MARKETING_CAMPAIGN: '/common/SET_MARKETING_CAMPAIGN',
  IS_MOBILE: '/common/IS_MOBILE',
  ENABLE_FEATURE: '/common/ENABLE_FEATURE',
  HIDE_HOW_IT_WORKS: '/common/HIDE_HOW_IT_WORKS',
  SHOW_SPINNER: '/common/SHOW_SPINNER',
  SET_SEGMENT_USER_ID: '/common/SET_SEGMENT_USER_ID'
};
