product:
  jobs:
  - lint
  - product_build:
      context: aws-non-prod
      filters:
        tags:
          only: /^product-v.*/
        branches:
          ignore: /.*/
  - hold:
      name: hold_<< matrix.env >>
      type: approval
      matrix:
        parameters:
          env: ["dev", "qa", "uat"]
      requires:
        - product_build
      filters:
        tags:
          only: /^product-v.*/
        branches:
          ignore: /.*/
  - product_deploy:
      name: product_deploy_<< matrix.env >>
      context: aws-non-prod
      matrix:
        parameters:
          env: ["dev", "qa", "uat"]
      requires:
        - hold_<< matrix.env >>
      filters:
        tags:
          only: /^product-v.*/
        branches:
          ignore: /.*/
  - hold:
      name: hold_prod
      type: approval
      requires:
        - product_deploy_dev
        - product_deploy_qa
        - product_deploy_uat
      filters:
        tags:
          only: /^product-v.*/
        branches:
          ignore: /.*/
  - product_deploy:
      name: product_deploy_prod
      context: aws-non-prod
      env: "prod"
      requires:
        - hold_prod
      filters:
        tags:
          only: /^product-v.*/
        branches:
          ignore: /.*/