const UPDATE = '/appraisal/UPDATE_ACTIVE_SELECTION';
const UPDATE_COMPLETED_SECTIONS = '/appraisal/UPDATE_COMPLETED_SECTIONS';
const UPDATE_FIELD = '/appraisal/UPDATE_FIELD';
const UPDATE_FIELDS = '/appraisal/UPDATE_FIELDS';
const CREATE_APPRAISAL_REQUEST = '/appraisal/CREATE_APPRAISAL_REQUEST';
const CREATE_APPRAISAL_SUCCESS = '/appraisal/CREATE_APPRAISAL_SUCCESS';
const CREATE_APPRAISAL_FAILURE = '/appraisal/CREATE_APPRAISAL_FAILURE';
const DECODE_VIN_REQUEST = '/appraisal/DECODE_VIN_REQUEST';
const DECODE_VIN_SUCCESS = '/appraisal/DECODE_VIN_SUCCESS';
const DECODE_VIN_FAILURE = '/appraisal/DECODE_VIN_FAILURE';
const GET_OPTIONS_REQUEST = '/appraisal/GET_OPTIONS_REQUEST';
const GET_OPTIONS_SUCCESS = '/appraisal/GET_OPTIONS_SUCCESS';
const GET_OPTIONS_FAILURE = '/appraisal/GET_OPTIONS_FAILURE';
const RESTART_APPRAISAL = '/appraisal/RESTART_APPRAISAL';
const SET_BRAND = '/appraisal/SET_BRAND';
const SET_DEALERSHIP = '/appraisal/SET_DEALERSHIP';
const SET_TYPE = '/appraisal/SET_TYPE';

const VEHICLE_INDEX = 0;
const HISTORY_INDEX = 1;
const INTERIOR_INDEX = 2;
const EXTERIOR_INDEX = 3;
const MECHANICAL_INDEX = 4;
const PERSONAL_INDEX = 5;
const NUM_SECTIONS = 6;

export default {
  UPDATE,
  UPDATE_COMPLETED_SECTIONS,
  UPDATE_FIELD,
  UPDATE_FIELDS,
  CREATE_APPRAISAL_REQUEST,
  CREATE_APPRAISAL_SUCCESS,
  CREATE_APPRAISAL_FAILURE,
  DECODE_VIN_REQUEST,
  DECODE_VIN_SUCCESS,
  DECODE_VIN_FAILURE,
  GET_OPTIONS_REQUEST,
  GET_OPTIONS_SUCCESS,
  GET_OPTIONS_FAILURE,
  RESTART_APPRAISAL,
  SET_BRAND,
  SET_DEALERSHIP,
  SET_TYPE
};

export {
  VEHICLE_INDEX,
  HISTORY_INDEX,
  INTERIOR_INDEX,
  EXTERIOR_INDEX,
  PERSONAL_INDEX,
  MECHANICAL_INDEX,
  NUM_SECTIONS
};
