version: 2
jobs:
  homepage: &mlp
    docker:
      - image: vroom/mlp:2.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          command: |-
            sudo apt-get install python-pip && pip install awscli
            aws s3 sync ./apps/homepage/public s3://homepage-assets-${CIRCLE_BRANCH//homepage-/}.n.vroom.systems --acl public-read
            build ./apps/homepage/docker
            deploy $CIRCLE_BRANCH ./apps/homepage/docker
  homepage_prod: &mlp
    docker:
      - image: vroom/mlp:2.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          command: |-
            sudo apt-get install python-pip && pip install awscli
            aws s3 sync ./apps/homepage/public s3://homepage-assets-${CIRCLE_BRANCH//homepage-/}.p.vroom.systems --acl public-read
            build ./apps/homepage/docker
            deploy $CIRCLE_BRANCH ./apps/homepage/docker
  lighthouse:
    docker:
      - image: circleci/node:erbium-alpine-browsers
    steps:
      - checkout
      - run:
          command: |-
            # Bootstrap yarn workspaces.
            yarn install --silent

            # Build libraries.
            yarn workspace @vroom-web/inv-search-networking build
            yarn workspace @vroom-web/ui build
            yarn workspace @vroom-web/header-components build
            yarn workspace @vroom-web/footer-components build

            # Build the main app.
            yarn workspace @vroom-web/homepage build

            nohup yarn workspace @vroom-web/homepage start --port 8080 & sleep 5

            yarn global add @lhci/cli@0.3.x
            cd apps/homepage
            /home/circleci/.yarn/bin/lhci autorun
workflows:
  version: 2
  workflow:
    jobs:
      - lighthouse:
            context: aws-prod
      - homepage:
          context: aws-non-prod
          filters:
            branches:
              only:
                - homepage-dev
                - homepage-qa
                - homepage-uat
      - homepage_prod:
          context: aws-prod
          filters:
            branches:
              only:
                - homepage-prod
