version: 2
jobs:
  homepage: &mlp
    docker:
      - image: vroom/mlp:3.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          # sudo apt-get install python-pip && pip install awscli
          # aws s3 sync ./apps/homepage/public s3://homepage-assets-${CIRCLE_BRANCH//homepage-/}.n.vroom.systems --acl public-read
          command: |-
            build -a vroom-web/apps/homepage/docker
            deploy -a vroom-web/apps/homepage/docker -n dev
  homepage_prod: &mlp
    docker:
      - image: vroom/mlp:2.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          command: |-
            sudo apt-get install python-pip && pip install awscli
            aws s3 sync ./apps/homepage/public s3://homepage-assets-${CIRCLE_BRANCH//homepage-/}.p.vroom.systems --acl public-read
            build ./apps/homepage/docker
            deploy $CIRCLE_BRANCH ./apps/homepage/docker
workflows:
  version: 2
  workflow:
    jobs:
      - homepage:
          context: aws-non-prod
          filters:
            branches:
              only:
                - homepage-dev
                - homepage-qa
                - homepage-uat
      - homepage_prod:
          context: aws-prod
          filters:
            branches:
              only:
                - homepage-prod
