version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  sonarcloud:
    docker:
      - image: circleci/node:erbium-browsers
    steps:
      - checkout
      - run:
          command: |-
            # Bootstrap yarn workspaces.
            yarn install --silent

            # Build libraries.
            yarn workspace @vroom-web/analytics-integration build
            yarn workspace @vroom-web/deals-v2-networking build
            yarn workspace @vroom-web/inv-search-networking build
            yarn workspace @vroom-web/ui build
            yarn workspace @vroom-web/header-components build
            yarn workspace @vroom-web/footer-components build

            # Build the main app.
            yarn workspace @vroom-web/homepage build
      - sonarcloud/scan
  danger:
    docker:
      - image: node:erbium-alpine
    steps:
      - checkout
      - run:
          name: Danger
          command: |-
            yarn install
            yarn danger ci
  lighthouse:
    docker:
      - image: circleci/node:erbium-browsers
    steps:
      - checkout
      - run:
          command: |-
            # Bootstrap yarn workspaces.
            yarn install --silent

            # Build libraries.
            yarn workspace @vroom-web/analytics-integration build
            yarn workspace @vroom-web/deals-v2-networking build
            yarn workspace @vroom-web/inv-search-networking build
            yarn workspace @vroom-web/ui build
            yarn workspace @vroom-web/header-components build
            yarn workspace @vroom-web/footer-components build

            # Build the main app.
            yarn workspace @vroom-web/homepage build

            nohup yarn workspace @vroom-web/homepage start --port 8080 & sleep 5

            yarn global add @lhci/cli@0.3.x
            cd apps/homepage
            /home/circleci/.yarn/bin/lhci autorun
  lint:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - run:
          command: |-
              # Bootstrap yarn workspaces.
              yarn install --silent

              yarn workspaces run lint
  homepage_build: &mlp
    docker:
      - image: vroom/mlp:3.0.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          command: |-
            build -a vroom-web/apps/homepage/docker
  homepage_deploy: &mlp
    docker:
      - image: vroom/mlp:3.0.1
    parameters:
      env:
        type: string
      s3:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          command: |-
            sudo apt-get install python-pip && pip install awscli

            aws s3 sync ./apps/homepage/public << parameters.s3 >> --acl public-read --exclude '*.webp' --exclude '*.mp4'
            aws s3 sync ./apps/homepage/public << parameters.s3 >> --acl public-read --exclude '*' --include '*.webp' --content-type 'image/webp'
            aws s3 sync ./apps/homepage/public << parameters.s3 >> --acl public-read --exclude '*' --include '*.mp4' --content-type 'video/mp4'

            login
            deploy -a vroom-web/apps/homepage/docker -n << parameters.env >>
workflows:
  version: 2
  homepage:
    jobs:
      - sonarcloud:
          context: SonarCloud
      - danger:
          context: dangerjs
      - lighthouse:
          context: aws-prod
      - lint
      - homepage_build:
          name: homepage_build-non-prod
          context: aws-non-prod
          filters:
            tags:
              only: /^homepage-v.*/
            branches:
              ignore: /.*/
      - hold:
          name: hold_<< matrix.env >>
          matrix:
            parameters:
              env: ["dev", "qa", "uat"]
          type: approval
          requires:
            - homepage_build-non-prod
          filters:
            tags:
              only: /^homepage-v.*/
            branches:
              ignore: /.*/
      - homepage_deploy:
          context: aws-non-prod
          s3: s3://homepage-assets-<< matrix.env >>.n.vroom.systems
          matrix:
            parameters:
              env: ["dev", "qa", "uat"]
          requires:
            - hold_<< matrix.env >>
          filters:
            tags:
              only: /^homepage-v.*/
            branches:
              ignore: /.*/
      - hold:
          name: hold_prod
          type: approval
          requires:
            - homepage_deploy-dev
            - homepage_deploy-qa
            - homepage_deploy-uat
          filters:
            tags:
              only: /^homepage-v.*/
            branches:
              ignore: /.*/
      - homepage_build:
          name: homepage_build-prod
          context: aws-prod
          requires:
            - hold_prod
          filters:
            tags:
              only: /^homepage-v.*/
            branches:
              ignore: /.*/
      - homepage_deploy:
          name: homepage_deploy-prod
          context: aws-prod
          env: "prod"
          s3: s3://homepage-assets-prod.p.vroom.systems
          requires:
            - homepage_build-prod
          filters:
            tags:
              only: /^homepage-v.*/
            branches:
              ignore: /.*/