jobs:
  danger:
    docker:
    - image: node:erbium-alpine
    steps:
    - checkout
    - run:
        command: |-
          yarn install
          yarn danger ci
        name: Danger
  home_build:
    docker:
    - image: vroom/mlp:3.0.2
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: build -a vroom-web/apps/home/docker
  home_deploy:
    docker:
    - image: vroom/mlp:3.0.2
    parameters:
      env:
        type: string
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: deploy -a vroom-web/apps/home/docker -n << parameters.env >>
  lint_build:
    docker:
    - image: circleci/node:erbium
    steps:
    - checkout
    - run:
        command: |-
          yarn install --silent
          yarn workspaces run lint
          yarn workspaces run build
        name: Lint & Build
  listing_build:
    docker:
    - image: vroom/mlp:3.0.2
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: build -a vroom-web/apps/listing/docker
  listing_deploy:
    docker:
    - image: vroom/mlp:3.0.2
    parameters:
      env:
        type: string
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: deploy -a vroom-web/apps/listing/docker -n << parameters.env >>
  marketing_build:
    docker:
    - image: vroom/mlp:3.0.2
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: build -a vroom-web/apps/marketing/docker
  marketing_deploy:
    docker:
    - image: vroom/mlp:3.0.2
    parameters:
      env:
        type: string
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: deploy -a vroom-web/apps/marketing/docker -n << parameters.env >>
  product_build:
    docker:
    - image: vroom/mlp:3.0.2
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: build -a vroom-web/apps/product/docker
  product_deploy:
    docker:
    - image: vroom/mlp:3.0.2
    parameters:
      env:
        type: string
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: deploy -a vroom-web/apps/product/docker -n << parameters.env >>
  sonarcloud:
    docker:
    - image: circleci/node:erbium-browsers
    steps:
    - checkout
    - run:
        command: |-
          # Bootstrap yarn workspaces.
          yarn install --silent

          # Build libraries.
          yarn workspace @vroom-web/analytics-integration build
          yarn workspace @vroom-web/catalog-url-integration build
          yarn workspace @vroom-web/deals-v2-networking build
          yarn workspace @vroom-web/inv-search-networking build
          yarn workspace @vroom-web/ui build
          yarn workspace @vroom-web/header-components build
          yarn workspace @vroom-web/footer-components build

          # Build the main app.
          yarn workspace @vroom-web/home build
    - sonarcloud/scan
  static-assets_deploy:
    docker:
    - image: vroom/mlp:3.0.2
    parameters:
      s3BucketUrl:
        type: string
    steps:
    - checkout
    - run:
        command: |-
          aws s3 sync ./static-assets << parameters.s3BucketUrl >> --acl public-read --exclude '*.webp' --exclude '*.mp4'
          aws s3 sync ./static-assets << parameters.s3BucketUrl >> --acl public-read --exclude '*' --include '*.webp' --content-type 'image/webp'
          aws s3 sync ./static-assets << parameters.s3BucketUrl >> --acl public-read --exclude '*' --include '*.mp4' --content-type 'video/mp4'
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
version: 2.1
workflows:
  common:
    jobs:
    - danger:
        context: dangerjs
    - lint_build
  home:
    jobs:
    - home_build:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^home-v.*/
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^home-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: hold_<< matrix.env >>
        requires:
        - home_build
        type: approval
    - home_deploy:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^home-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: home_deploy_<< matrix.env >>
        requires:
        - hold_<< matrix.env >>
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^home-v.*/
        name: hold_prod
        requires:
        - home_deploy_dev
        - home_deploy_qa
        - home_deploy_uat
        type: approval
    - home_deploy:
        context: aws-non-prod
        env: prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^home-v.*/
        name: home_deploy_prod
        requires:
        - hold_prod
  listing:
    jobs:
    - listing_build:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^listing-v.*/
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^listing-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: hold_<< matrix.env >>
        requires:
        - listing_build
        type: approval
    - listing_deploy:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^listing-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: listing_deploy_<< matrix.env >>
        requires:
        - hold_<< matrix.env >>
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^listing-v.*/
        name: hold_prod
        requires:
        - listing_deploy_dev
        - listing_deploy_qa
        - listing_deploy_uat
        type: approval
    - listing_deploy:
        context: aws-non-prod
        env: prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^listing-v.*/
        name: listing_deploy_prod
        requires:
        - hold_prod
  marketing:
    jobs:
    - marketing_build:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^marketing-v.*/
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^marketing-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: hold_<< matrix.env >>
        requires:
        - marketing_build
        type: approval
    - marketing_deploy:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^marketing-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: marketing_deploy_<< matrix.env >>
        requires:
        - hold_<< matrix.env >>
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^marketing-v.*/
        name: hold_prod
        requires:
        - marketing_deploy_dev
        - marketing_deploy_qa
        - marketing_deploy_uat
        type: approval
    - marketing_deploy:
        context: aws-non-prod
        env: prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^marketing-v.*/
        name: marketing_deploy_prod
        requires:
        - hold_prod
  product:
    jobs:
    - product_build:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^product-v.*/
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^product-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: hold_<< matrix.env >>
        requires:
        - product_build
        type: approval
    - product_deploy:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^product-v.*/
        matrix:
          parameters:
            env:
            - dev
            - qa
            - uat
        name: product_deploy_<< matrix.env >>
        requires:
        - hold_<< matrix.env >>
    - hold:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^product-v.*/
        name: hold_prod
        requires:
        - product_deploy_dev
        - product_deploy_qa
        - product_deploy_uat
        type: approval
    - product_deploy:
        context: aws-non-prod
        env: prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^product-v.*/
        name: product_deploy_prod
        requires:
        - hold_prod
  static-assets:
    jobs:
    - static-assets_deploy:
        context: aws-non-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^static-assets-v.*/
        name: static-assets_deploy-non-prod
        s3BucketUrl: s3://static-assets.n.vroom.systems
    - static-assets_deploy:
        context: aws-prod
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^static-assets-v.*/
        name: static-assets_deploy-prod
        s3BucketUrl: s3://static-assets.p.vroom.systems
  version: 2

