jobs:
    appraisal_build:
        docker:
            - image: vroom/mlp:3.0.2
        steps:
            - checkout
            - setup_remote_docker:
                version: 18.09.3
            - run:
                command: build -a appraisal/docker
    appraisal_deploy:
        docker:
            - image: vroom/mlp:3.0.2
        parameters:
            env:
                type: string
        steps:
            - checkout
            - setup_remote_docker:
                version: 18.09.3
            - run:
                command: deploy -a appraisal/docker -n << parameters.env >>
version: 2.1
workflows:
    appraisal:
        jobs:
            - appraisal_build:
                context: aws-non-prod
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^appraisal-v.*/
            - hold:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^appraisal-v.*/
                matrix:
                    parameters:
                        env:
                            - dev
                            - qa
                            - uat
                name: hold_<< matrix.env >>
                requires:
                    - appraisal_build
                type: approval
            - appraisal_deploy:
                context: aws-non-prod
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^appraisal-v.*/
                matrix:
                    parameters:
                        env:
                            - dev
                            - qa
                            - uat
                name: appraisal_deploy_<< matrix.env >>
                requires:
                    - hold_<< matrix.env >>
            - hold:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^appraisal-v.*/
                name: hold_prod
                requires:
                    - appraisal_deploy_dev
                    - appraisal_deploy_qa
                    - appraisal_deploy_uat
                type: approval
            - appraisal_deploy:
                context: aws-non-prod
                env: prod
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^appraisal-v.*/
                name: appraisal_deploy_prod
                requires:
                    - hold_prod
