danger:
  docker:
    - image: node:erbium-alpine
  steps:
    - checkout
    - run:
        name: Danger
        command: |-
          yarn install
          yarn danger ci
lint_build:
  docker:
    - image: circleci/node:erbium
  steps:
    - checkout
    - run:
        name: Lint & Build
        command: |-
          yarn install --silent
          yarn workspaces run lint
          yarn workspaces run build
