sonarcloud:
  docker:
  - image: circleci/node:erbium-browsers
  steps:
    - checkout
    - run:
        command: |-
          # Bootstrap yarn workspaces.
          yarn install --silent

          # Build libraries.
          yarn workspace @vroom-web/analytics-integration build
          yarn workspace @vroom-web/catalog-url-integration build
          yarn workspace @vroom-web/deals-v2-networking build
          yarn workspace @vroom-web/inv-search-networking build
          yarn workspace @vroom-web/ui build
          yarn workspace @vroom-web/header-components build
          yarn workspace @vroom-web/footer-components build

          # Build the main app.
          yarn workspace @vroom-web/homepage build
    - sonarcloud/scan
homepage_build:
  docker:
  - image: vroom/mlp:3.0.2
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: |-
          build -a vroom-web/apps/homepage/docker
homepage_deploy:
  docker:
  - image: vroom/mlp:3.0.2
  parameters:
    env:
      type: string
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: |-
          deploy -a vroom-web/apps/homepage/docker -n << parameters.env >>

          # sleep 240
          # if [ -z "${FASTLY_PURGE_KEY}" ]; then echo "FASTLY_PURGE_KEY not set"; return 1; elif [ -z "${FASTLY_SERVICE_ID}" ]; then echo "FASTLY_SERVICE_ID not set"; return 1; else echo "Purging Fastly for service ${FASTLY_SERVICE_ID}"; curl -X POST -H "Fastly-Key: ${FASTLY_PURGE_KEY}" -H "Accept: application/json" https://api.fastly.com/service/${FASTLY_SERVICE_ID}/purge_all ; fi