sonarcloud:
  docker:
  - image: circleci/node:erbium-browsers
  steps:
    - checkout
    - run:
        command: |-
          # Bootstrap yarn workspaces.
          yarn install --silent

          # Build libraries.
          yarn workspace @vroom-web/analytics-integration build
          yarn workspace @vroom-web/deals-v2-networking build
          yarn workspace @vroom-web/inv-search-networking build
          yarn workspace @vroom-web/ui build
          yarn workspace @vroom-web/header-components build
          yarn workspace @vroom-web/footer-components build

          # Build the main app.
          yarn workspace @vroom-web/homepage build
    - sonarcloud/scan
homepage_build:
  docker:
  - image: vroom/mlp:3.0.1
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: |-
          build -a vroom-web/apps/homepage/docker
homepage_deploy:
  docker:
  - image: vroom/mlp:3.0.1
  parameters:
    env:
      type: string
    s3:
      type: string
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: |-
          sudo apt-get install python-pip && pip install awscli

          SHORT_HASH=$(git rev-parse --short HEAD)

          aws s3 sync ./apps/homepage/.next/static << parameters.s3 >>/$SHORT_HASH --acl public-read
          aws s3 sync ./apps/homepage/public << parameters.s3 >>/$SHORT_HASH --acl public-read --exclude '*.webp' --exclude '*.mp4'
          aws s3 sync ./apps/homepage/public << parameters.s3 >>/$SHORT_HASH --acl public-read --exclude '*' --include '*.webp' --content-type 'image/webp'
          aws s3 sync ./apps/homepage/public << parameters.s3 >>/$SHORT_HASH --acl public-read --exclude '*' --include '*.mp4' --content-type 'video/mp4'

          login
          deploy -a vroom-web/apps/homepage/docker -n << parameters.env >>