sonarcloud:
  docker:
  - image: circleci/node:erbium-browsers
  steps:
    - checkout
    - run:
        command: |-
          # Bootstrap yarn workspaces.
          yarn install --silent

          # Build the main app.
          yarn workspace @vroom-web/logistics build
    - sonarcloud/scan
logistics_build:
  docker:
  - image: vroom/mlp:3.0.2
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: |-
          build -a vroom-web/apps/logistics/docker
logistics_deploy:
  docker:
  - image: vroom/mlp:3.0.2
  parameters:
    env:
      type: string
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: |-
          deploy -a vroom-web/apps/logistics/docker -n << parameters.env >>
