static-assets_deploy:
  docker:
  - image: vroom/mlp:3.0.2
  steps:
    - checkout
    - run:
        command: |-
          aws s3 sync ./static-assets s3://static-assets.p.vroom.systems --acl public-read --exclude '*.webp' --exclude '*.mp4'
          aws s3 sync ./static-assets s3://static-assets.p.vroom.systems --acl public-read --exclude '*' --include '*.webp' --content-type 'image/webp'
          aws s3 sync ./static-assets s3://static-assets.p.vroom.systems --acl public-read --exclude '*' --include '*.mp4' --content-type 'video/mp4'
