export const checkoutTradeTypes = {
  GET_CARFAX: '/checkoutTradeTypes/GET_CARFAX',
  GET_OFFER_DATA: '/checkoutTradeTypes/GET_OFFER_DATA',
  SET_OFFER_DATA: '/checkoutTradeTypes/SET_OFFER_DATA',
  GET_OFFER_DETAILS: '/checkoutTradeTypes/GET_OFFER_DETAILS',
  GET_LICENSE_TO_VIN: '/checkoutTradeTypes/GET_LICENSE_TO_VIN',
  SELECT_VIN_FROM_MANY: '/checkoutTradeTypes/SELECT_VIN_FROM_MANY',
  GET_MULTIPLE_VINS_FROM_LP: '/checkoutTradeTypes/GET_MULTIPLE_VINS_FROM_LP',
  SET_APPRAISAL_INFO: '/checkoutTradeTypes/SET_APPRAISAL_INFO',
  UPDATE_APPRAISAL_INFO: '/checkoutTradeTypes/UPDATE_APPRAISAL_INFO',
  REFRESH_APPRAISAL_INFO: '/checkoutTradeTypes/REFRESH_APPRAISAL_INFO',
  SET_YEAR_MAKE_MODEL: '/checkoutTradeTypes/SET_YEAR_MAKE_MODEL',
  RECEIVED_REAL_TIME_OFFER: '/checkoutTradeTypes/RECEIVED_REAL_TIME_OFFER',
  NEXT_EXPIRING_OFFER: '/checkoutTradeTypes/NEXT_EXPIRING_OFFER',
  DISMISS_EXPIRING_SOON_DIALOG:
    '/checkoutTradeTypes/DISMISS_EXPIRING_SOON_DIALOG',
  DISMISS_EXACT_MILEAGE_DIALOG:
    '/checkoutTradeTypes/DISMISS_EXACT_MILEAGE_DIALOG',
  DECODE_VIN: '/checkoutTradeTypes/DECODE_VIN',
  GRADE_CHECK: '/checkoutTradeTypes/GRADE_CHECK',
};
