ingress:
  enabled: true
  tls:
    enabled: false

resources:
  limits:
    cpu: "1"
    memory: 1G
  requests:
    cpu: "1"
    memory: 1G

service:
  externalPort: 8080
  internalPort: 8080

livenessProbe:
  path: '/appraisal/api/version'

readinessProbe:
  path: '/appraisal/api/version'

podAnnotations:
  ad.datadoghq.com/auto-deploy-app.check_names: '["auto-deploy-app"]'
  ad.datadoghq.com/auto-deploy-app.init_configs: '[{}]'
  ad.datadoghq.com/auto-deploy-app.instances: '[{"host": "%%host%%", "port": "%%port%%"}]'
  ad.datadoghq.com/auto-deploy-app.logs: '[{"source": "appraisal", "service": "appraisal"}]'
