version: '3'
services:
  marketing:
    build:
      context: ../../../
      dockerfile: ./apps/marketing/docker/Dockerfile
    user: 'root'
    environment:
      - CALENDLY_URL=https://calendly.com/vroom-test/phone-call
      - CREATE_ZENDESK_REQUEST_URL=https://vroom.zendesk.com/api/v2/requests.json
      - GEARBOX_PRIVATE_URL=https://gearbox-dev-int.vroomapi.com/query-private
      - SANTANDER_SEGMENT_WRITE_KEY=BP2otWcD2EbECrCfUwn1RuDQAPPYa6mv
      - SEGMENT_WRITE_KEY=N0pxERRIw4iYCoxZREMZj1yWBIoARIz4
      - STATIC_ASSETS_HOST_URL=https://static-assets.n.vroom.systems
      - TDA_SEGMENT_WRITE_KEY=TbYgIIsercszeyRUCwgE2F3mOWV9QMjb
    command: ash -c "yarn workspace @vroom-web/marketing dev --port 8080"
    # This starts nothing but leaves the container running, useful for
    # debugging nextjs start / config operations
    # command: ash -c "tail -f /dev/null"
    ports:
      - '8080:8080'
    volumes:
      # Setup a volume so source code edits will be reflected outside the container.
      - '../../../:/www/'
      # Setup volumes for dependencies and built artifacts.
      # This allows the node_modules created during the build to not be overwritten.
      # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
      # It also makes sure that the built artifacts are only present on the container,
      # and not copied back to the host machine.
      - '/www/node_modules'
      - '/www/apps/marketing/.next'
      - '/www/apps/marketing/node_modules'
