const ENVS = {
  BASE_PATH: process.env.NEXT_PUBLIC_BASE_PATH || '',
  GEARBOX_PRIVATE_URL: process.env.NEXT_PUBLIC_GEARBOX_PRIVATE_URL || '',
  DATA_DOG_RUM_APPLICATION:
    process.env.NEXT_PUBLIC_DATA_DOG_RUM_APPLICATION || '',
  DATA_DOG_RUM_TOKEN: process.env.NEXT_PUBLIC_DATA_DOG_RUM_TOKEN || '',
  SEGMENT_WRITE_KEY: process.env.SEGMENT_WRITE_KEY || '',
  VROOM_URL: process.env.NEXT_PUBLIC_VROOM_URL || '',
  STATIC_ASSETS_HOST_URL: process.env.NEXT_PUBLIC_STATIC_ASSETS_HOST_URL || '',
  BRANCH_IO_KEY: process.env.NEXT_PUBLIC_BRANCH_IO_KEY || '',
};

export default ENVS;
