export default {
  automated_appraisal: false,
  ID: 'dGhpc2lzZmFrZW5vcHJpY2VvZmZlcg',
  Price__c: 0,
  xke_user_id: 0,
  Year__c: 0,
  Make__c: '',
  Model__c: '',
  Trim__c: '',
  miles: 0,
  Good_Until__c: null,
  VIN__c: '',
  offer_id: 0,
  offer_status_id: 0,
  vehicle_id: 0,
  created: new Date().toISOString(),
  offer_status: 'Submitted',
  user_email: 'support@vroom.com',
  active: true,
  new_offer: true,
  verification_url: null,
  tax_credit_savings: null,
  payment_method: null,
  grade: 'WHOLESALE',
  blend_retail: null,
  experiment_ids: null,
  sf_offer_id: null,
  zipcode: '',
  form: null,
};
