export const authActions = {
  LOGIN_REQUEST: '/login/LOGIN_REQUEST',
  LOGIN_SUCCESS: '/login/LOGIN_SUCCESS',
  REQUEST_TOKEN: '/login/REQUEST_TOKEN',
  REFRESH_ACCESS_TOKEN: '/login/REFRESH_ACCESS_TOKEN',
  LOGIN_FAILURE: '/login/LOGIN_FAILURE',
  LOGOUT_REQUEST: '/login/LOGOUT_REQUEST',
  LOGOUT_SUCCESS: '/login/LOGOUT_SUCCESS',
  LOGOUT_FAILURE: '/login/LOGOUT_FAILURE',
  SET_USER_INFO: '/login/SET_USER_INFO',
  SHOW_CK: '/login/SHOW_CK',
  SET_SIGNIN_STATUS: '/login/SET_SIGNIN_STATUS',
  SET_USER_INFO_STATUS: '/login/SET_USER_INFO_STATUS'
};

export const userActions = {
  GET_FAVORITES: '/user/GET_FAVORITES',
  GET_FAVORITE_VEHICLES: '/user/GET_FAVORITE_VEHICLES',
  ADD_FAVORITES: '/user/ADD_FAVORITES',
  SET_FAVORITES_LIST: '/user/SET_FAVORITES_LIST',
  REMOVE_FAVORITES: '/user/REMOVE_FAVORITES',
  ADD_NEW_ADDRESS: '/user/ADD_NEW_ADDRESS',
  UPDATE_ADDRESS: '/user/UPDATE_ADDRESS',
  GET_TRANSACTIONS: '/user/GET_TRANSACTIONS',
  SET_DEAL_ID: './user/SET_DEAL_ID',
  SET_DOCUMENT: '/user/SET_DOCUMENT',
  SET_DOCUMENTS_LIST: '/user/SET_DOCUMENTS_LIST',
  REMOVE_DOCUMENTS: '/user/REMOVE_DOCUMENTS'
};

export const Status = {
  INITIAL: 'initial',
  LOADING: 'loading',
  SUCCESS: 'success',
  ERROR: 'error'
};
